### ISSUE TITLE
Cache Busting

### ISSUE THREAD

**Issue by rpalcolea** [sysgears/grain#19]
Hi! 

I have one question, what's the best way to do cache busting with Grain? Is there a way you recommend?

I know that one part should be done at server level to add the proper headers in the response for cache, but what about add version to the JS/CSS/images URLS? Is that a thing we could do with Grain?

This is more to know if you could recommend / give and advice of how to handle that. I usually work with Grails and leverage that to asset-pipeline.

Thanks

**Comment by vlasenko** [comment]
Hi Roberto,

Yes, you can do this with Grain. We do it for website of our company. To explain how you can do it we need some time, because the answer is not trivial. Please post this question into Grain User Group so that the answer were accessible for all Grain Users, thanks!
https://groups.google.com/forum/#!forum/grain-user

Victor

**Comment by rpalcolea** [comment]
Thanks @vlasenko https://groups.google.com/forum/#!topic/grain-user/rdZYbNnfucM
